# Generated by Django 4.0.4 on 2022-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='s', max_length=50)),
                ('article_news_block', models.CharField(default='article_news_block', max_length=50, verbose_name='Блок')),
                ('article_news_title', models.CharField(default='article_news_title', max_length=50, verbose_name='Название')),
                ('article_news_body', models.CharField(default='article_news_body', max_length=50, verbose_name='Контент')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готовность к скачиванию')),
                ('has_error', models.BooleanField(default=False, verbose_name='Наличие ошибки')),
                ('error_body', models.CharField(default='Непредвиденная ошибка', max_length=50, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
