# Generated by Django 4.0.4 on 2022-05-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_searchedlink_error_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlink',
            name='error_body',
        ),
        migrations.RemoveField(
            model_name='searchedlink',
            name='has_error',
        ),
    ]
