# Generated by Django 4.0.4 on 2022-05-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_searchedlink_error_body_searchedlink_has_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlink',
            name='error_body',
        ),
    ]
