# Generated by Django 4.0.4 on 2022-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_remove_searchedlink_error_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedlink',
            name='error_body',
            field=models.CharField(default='', max_length=100, verbose_name='Ошибка'),
        ),
    ]
