# Generated by Django 4.0.4 on 2022-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_searchedlink_error_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedlink',
            name='error_body',
            field=models.CharField(max_length=100, verbose_name='Ошибка'),
        ),
    ]
