# Generated by Django 4.0.4 on 2022-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_alter_searchedlink_error_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlink',
            name='error_body',
        ),
        migrations.AddField(
            model_name='searchedlink',
            name='eerror_body',
            field=models.TextField(default='', max_length=100, verbose_name='Ошибка'),
        ),
    ]
