# Generated by Django 4.0.4 on 2022-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_remove_searchedlink_error_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchedlink',
            name='eerror_body',
        ),
        migrations.AddField(
            model_name='searchedlink',
            name='error_body',
            field=models.CharField(default='', max_length=70, verbose_name='Ошибка'),
        ),
    ]
