# Generated by Django 4.0.4 on 2022-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_alter_user_requested_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested_object_id',
            field=models.IntegerField(default=0, verbose_name='object ID'),
        ),
    ]
