# Generated by Django 4.0.4 on 2022-05-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_alter_user_requested_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
